### ISSUE TITLE
debconf: delaying package configuration, since apt-utils is not installed

### ISSUE THREAD

**Issue by hbakhtiyor** [yukinying/chrome-headless-browser-docker#13]
getting the warnings

```
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.20.2 /usr/local/share/perl/5.20.2 /usr/lib/x86_64-linux-gnu/perl5/5.20 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.20 /usr/share/perl/5.20 /usr/local/lib/site_perl .) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
```

**Comment by yukinying** [comment]
Are you running the chrome-headless-browser or chrome-headless-browser-selenium? It would help if you could provide the step to reproduce that.

**Comment by hbakhtiyor** [comment]
only chrome-headless-browser, and it's during building image, just copy the dockerfile and build on my local machine

**Comment by yukinying** [comment]
I see what you mean now. I think the way to fix that is to add `DEBIAN_FRONTEND=noninteractive` before the apt-get command.

**Comment by hbakhtiyor** [comment]
will you add it?

**Comment by yukinying** [comment]
I don't really want to add an extra ENV as people may use this as a base. As long as this is not breaking a build, I think I can take more time trying to find out the best practice. I am looking at whether using ARG make more sense.

**Comment by yukinying** [comment]
Fixed in https://github.com/yukinying/chrome-headless-browser-docker/commit/6a081f5720911c58b5fd3124da9dc95fb498682f

**Comment by hbakhtiyor** [comment]
@yukinying  still getting `debconf: delaying package configuration, since apt-utils is not installed`
also 

```
Warning: apt-key output should not be parsed (stdout is not a terminal)

```
